export const navigationData = [
    {
        title: "About",
        href: "/about",
        icon: "Info",
        description: "Discover our legacy, leadership, and commitment to excellence.",
        items: [
            { title: "Overview", href: "/about/overview", icon: "LayoutDashboard", description: "A brief introduction to IAER." },
            { title: "Our Identity", href: "/about/identity", icon: "Fingerprint", description: "Who we are and what we stand for." },
            { title: "Vision and Mission", href: "/about/vision-mission", icon: "Target", description: "Our goals and guiding principles." },
            { title: "Leadership", href: "/about/leadership", icon: "Users", description: "Meet the minds behind IAER." },
            { title: "Governance", href: "/about/governance", icon: "Gavel", description: "Our administrative structure." },
            { title: "Recognition and Approvals", href: "/about/recognition", icon: "Award", description: "Affiliations and accreditations." },
            { title: "Awards and Rankings", href: "/about/awards", icon: "Trophy", description: "Celebrating our achievements." },
            { title: "Institutional Social Responsibility", href: "/about/social-responsibility", icon: "HeartHandshake", description: "Giving back to society." },
        ],
    },
    {
        title: "Programs",
        href: "/programs",
        icon: "GraduationCap",
        description: "Explore our diverse range of undergraduate and postgraduate courses.",
        items: [
            {
                title: "Undergraduate",
                href: "/programs/undergraduate",
                icon: "Book",
                subItems: [
                    { title: "BBA", href: "/programs/undergraduate/bba", icon: "Briefcase" },
                    { title: "BBA Hospital Management", href: "/programs/undergraduate/bba-hospital-management", icon: "Stethoscope" },
                    { title: "BBA Global Business", href: "/programs/undergraduate/bba-global-business", icon: "Globe" },
                    { title: "BBA Aviation", href: "/programs/undergraduate/bba-aviation", icon: "Plane" },
                    { title: "BBA Business Analytics", href: "/programs/undergraduate/bba-business-analytics", icon: "BarChart" },
                    { title: "BCA", href: "/programs/undergraduate/bca", icon: "Monitor" },
                    { title: "BSc Data Science", href: "/programs/undergraduate/bsc-data-science", icon: "Database" },
                    { title: "BSc Cyber Security", href: "/programs/undergraduate/bsc-cyber-security", icon: "ShieldCheck" },
                    { title: "BSc Hospitality", href: "/programs/undergraduate/bsc-hospitality", icon: "Utensils" },
                    { title: "BMLT", href: "/programs/undergraduate/bmlt", icon: "FlaskConical" },
                ],
            },
            {
                title: "Post Graduate",
                href: "/programs/post-graduate",
                icon: "BookOpen",
                subItems: [
                    { title: "MBA", href: "/programs/post-graduate/mba", icon: "TrendingUp" },
                ],
            },
            {
                title: "Certificate",
                href: "/programs/certificate",
                icon: "Award",
                subItems: [
                    { title: "Airport Ground Service", href: "/programs/certificate/airport-ground-service", icon: "PlaneLanding" },
                    { title: "Airlines Cabin Crew", href: "/programs/certificate/airlines-cabin-crew", icon: "UserCheck" },
                    { title: "Generative AI", href: "/programs/certificate/generative-ai", icon: "Cpu" },
                    { title: "Software Developer", href: "/programs/certificate/software-developer", icon: "Code" },
                    { title: "Full Stack Development", href: "/programs/certificate/full-stack-development", icon: "Layers" },
                    { title: "Medical Lab Technician", href: "/programs/certificate/medical-lab-technician", icon: "TestTube" },
                ],
            },
        ],
    },
    {
        title: "Academics",
        href: "/academics",
        icon: "Library",
        description: "Detailed information about our academic structure and practices.",
        items: [
            { title: "Academics Overview", href: "/academics/overview", icon: "Layout" },
            { title: "Program (Courses)", href: "/academics/programs", icon: "List" },
            { title: "Academic Calendar", href: "/academics/calendar", icon: "Calendar" },
            { title: "List of Holidays", href: "/academics/holidays", icon: "CalendarOff" },
            { title: "Teaching Practices", href: "/academics/teaching-practices", icon: "PenTool" },
            { title: "System of Evaluation", href: "/academics/evaluation", icon: "ClipboardCheck" },
            { title: "Professional Bodies", href: "/academics/professional-bodies", icon: "Building2" },
            { title: "Professors of Practice", href: "/academics/professors-of-practice", icon: "UserPlus" },
        ],
    },
    {
        title: "Admissions",
        href: "/admissions",
        icon: "FileText",
        description: "Start your journey with us. Application process, fees, and scholarships.",
        items: [
            { title: "Overview", href: "/admissions/overview", icon: "Info" },
            { title: "Course Fee", href: "/admissions/course-fee", icon: "Banknote" },
            { title: "How to Apply?", href: "/admissions/how-to-apply", icon: "HelpCircle" },
            { title: "Admission Criteria", href: "/admissions/eligibility", icon: "CheckSquare" },
            { title: "IAER Scholarships", href: "/admissions/scholarships", icon: "GraduationCap" },
            { title: "Education Loan", href: "/admissions/education-loan", icon: "Coins" },
            { title: "Hostel Fee", href: "/admissions/hostel-fee", icon: "Home" },
            { title: "Campus Life", href: "/admissions/campus-life", icon: "Smile" },
        ],
    },
    {
        title: "Placements",
        href: "/placements",
        icon: "Briefcase",
        description: "Our commitment to your career. Records, activities, and training.",
        items: [
            { title: "Highlights", href: "/placements/highlights", icon: "Star" },
            { title: "Placement Records", href: "/placements/records", icon: "FileBarChart" },
            { title: "Placement Activities", href: "/placements/activities", icon: "Activity" },
            { title: "Training Programs", href: "/placements/training", icon: "BookOpenCheck" },
            { title: "Industry Visits", href: "/placements/industry-visits", icon: "Bus" },
        ],
    },
    {
        title: "Research",
        href: "/research-and-innovation",
        icon: "Microscope",
        description: "Fostering innovation and new ideas.",
        items: [
            { title: "IAER Launchpad", href: "/research-and-innovation/launchpad", icon: "Rocket", description: "Business Startup Incubation Centre" },
            { title: "IAER InnovateX", href: "/research-and-innovation/innovatex", icon: "Zap", description: "IAER Tech Innovation Lab" },
        ],
    },
];
