export const navigationData = [
    {
        title: "About",
        href: "/about",
        icon: "Info",
        description: "Discover our legacy, leadership, and commitment to excellence.",
        image: "/images/about/building-image-about-hero.webp",
        items: [
            { title: "Overview", href: "/about#about-overview", icon: "LayoutDashboard", description: "A brief introduction to IAER." },
            { title: "Board of Governors", href: "/about/board-of-governors", icon: "Users", description: "Strategic leadership and governance." },
            { title: "Statutory Committees", href: "/about/statutory-committees", icon: "Gavel", description: "Ensuring compliance and student welfare." },
            { title: "Practical Education", href: "/about#about-practical", icon: "Zap", description: "Skill-based learning approach." },
            { title: "Industry Engagement", href: "/about#about-industry", icon: "Handshake", description: "Corporate connections & partnerships." },
            { title: "Our Identity", href: "/about#about-identity", icon: "Fingerprint", description: "Who we are and what we stand for." },
            { title: "Vision and Mission", href: "/about#about-vision", icon: "Target", description: "Our goals and guiding principles." },
            { title: "Recognition and Approvals", href: "/about#about-recognition", icon: "Award", description: "Affiliations and accreditations." },
            { title: "Awards and Rankings", href: "/about#about-awards", icon: "Trophy", description: "Celebrating our achievements." },
            { title: "Institutional Social Responsibility", href: "/about#about-isr", icon: "HeartHandshake", description: "Giving back to society." },
        ],
    },
    {
        title: "Programs",
        href: "/programs",
        icon: "GraduationCap",
        description: "Find the right program for your career goals.",
        image: "/images/programs/iaer-program-mega-menu.webp",
        items: [
            {
                title: "Undergraduate Degrees",
                href: "/programs",
                icon: "Book",
                subItems: [
                    { title: "BBA (Business Administration)", href: "/programs/bba-college-kolkata", icon: "Briefcase", description: "Learn core management, marketing, HR, and finance." },
                    { title: "BBA in Business Analytics", href: "/programs/bba-business-analytics-kolkata", icon: "BarChart3", description: "Management degree with data analytics and BI skills." },
                    { title: "BBA in Sports Management", href: "/programs/bba-sports-management-kolkata", icon: "Trophy", description: "Build a career in sports business, events, and marketing." },
                    { title: "BBA in Hospital Management", href: "/programs/bba-hospital-management-kolkata", icon: "Stethoscope", description: "Healthcare operations, administration, and management roles." },
                    { title: "BBA in Global Business", href: "/programs/bba-global-business-kolkata", icon: "Globe", description: "International business, trade, and global careers." },
                    { title: "BBA in Aviation Operations", href: "/programs/bba-in-aviation-operations", icon: "Plane", description: "Airport and airline operations with business fundamentals." },
                    { title: "BBA in Aviation & Hospitality", href: "/programs/bba-aviation-hospitality-management-kolkata", icon: "PlaneTakeoff", description: "Aviation + hospitality management for service careers." },
                    { title: "BCA (Computer Applications)", href: "/programs/bca-college-kolkata", icon: "Monitor", description: "Programming, software development, and IT foundations." },
                    { title: "BCA in AI & ML", href: "/programs/bca-ai-ml-kolkata", icon: "Brain", description: "AI, machine learning, and future tech skills." },
                    { title: "BCA in Data Science & Cyber Security", href: "/programs/bca-data-science-cyber-security-kolkata", icon: "ShieldAlert", description: "Analytics + cyber security in one specialization." },
                    { title: "B.Sc. Data Science", href: "/programs/bsc-data-science-kolkata", icon: "Database", description: "Statistics + programming for analytics and AI careers." },
                    { title: "B.Sc. Cyber Security", href: "/programs/bsc-cyber-security-kolkata", icon: "ShieldCheck", description: "Cyber security, ethical hacking, and network defense." },
                    { title: "B.Sc. Hospitality & Hotel Administration", href: "/programs/bsc-hospitality-hotel-management-kolkata", icon: "Utensils", description: "Hotel operations, hospitality, and service management." },
                    { title: "BMLT (Medical Lab Technology)", href: "/programs/bmlt-medical-lab-technology-kolkata", icon: "FlaskConical", description: "Medical lab science and diagnostic career pathways." },
                ],
            },
            {
                title: "Certificates & Diplomas",
                href: "/programs",
                icon: "Award",
                subItems: [
                    { title: "Software Development (Certificate)", href: "/programs/software-development-course-kolkata", icon: "Code", description: "Learn coding fundamentals for entry-level tech roles." },
                    { title: "Full Stack Development (Certificate)", href: "/programs/full-stack-development-course-kolkata", icon: "Layers", description: "Build websites and apps with frontend + backend skills." },
                    { title: "Agentic AI (Certificate)", href: "/programs/agentic-ai-course-kolkata", icon: "Brain", description: "Learn AI, GenAI, and automation with hands-on projects." },
                    { title: "Airline Cabin Crew (Certificate)", href: "/programs/cabin-crew-training-kolkata", icon: "Plane", description: "Cabin crew training for aviation service careers." },
                    { title: "Aviation & Hospitality (Diploma)", href: "/programs/diploma-aviation-hospitality-kolkata", icon: "Hotel", description: "Job-oriented diploma in aviation and hospitality." },
                    { title: "Medical Lab Technology (Diploma - DMLT)", href: "/programs/dmlt-course-kolkata", icon: "FlaskConical", description: "Start a healthcare diagnostic career in 2 years." },
                ],
            },
            {
                title: "Postgraduate Degrees",
                href: "/programs",
                icon: "BookOpen",
                subItems: [
                    { title: "MBA (Master of Business Administration)", href: "/programs/mba-college-kolkata", icon: "TrendingUp", description: "Advance your management career with an MBA." },
                    { title: "PGDM (Management)", href: "/programs/post-graduate-diploma-in-management-pgdm", icon: "BookOpen", description: "Industry-focused PG diploma for corporate careers." },
                    { title: "PGDM in AI & Data Science", href: "/programs/pgdm-in-ai-and-data-science", icon: "Cpu", description: "Management + AI and data skills for modern roles." },
                    { title: "PGDM in Business Analytics", href: "/programs/pgdm-ba", icon: "BarChart", description: "Become a data-driven business decision-maker." },
                    { title: "PGDM in FinTech", href: "/programs/pgdm-in-fintech", icon: "Coins", description: "Finance + technology for banking and fintech careers." },
                    { title: "PGDM in Hospital Management", href: "/programs/pgdm-in-hospital-management-health-administration", icon: "Activity", description: "Healthcare management roles in hospitals and services." },
                    { title: "MHA (Master of Hospital Administration)", href: "/programs/mha-hospital-management-kolkata", icon: "Activity", description: "Postgraduate degree for hospital administration careers." },
                ],
            },
        ],
    },
    {
        title: "Academics",
        href: "/academics",
        icon: "Library",
        description: "How learning works at IAER: curriculum, calendar, and evaluation.",
        image: "/images/academic/academic-mega-menu-image.webp",
        items: [
            { title: "Academics Overview", href: "/academics#academics-overview", icon: "Layout" },
            { title: "All Programs", href: "/programs", icon: "List" },
            { title: "Academic Calendar", href: "/academics#academics-calendar", icon: "Calendar" },
            { title: "List of Holidays", href: "/academics#academics-holidays", icon: "CalendarOff" },
            { title: "Teaching Practices", href: "/academics#academics-teaching-practices", icon: "PenTool" },
            { title: "System of Evaluation", href: "/academics#academics-evaluation", icon: "ClipboardCheck" },
            { title: "Professional Bodies", href: "/academics/professional-bodies", icon: "Building2" },
            { title: "Industry Professors", href: "/academics/professors-of-practice", icon: "UserPlus" },
        ],
    },
    {
        title: "Admissions",
        href: "/admissions",
        icon: "FileText",
        description: "Start your journey with us. Application process, fees, and scholarships.",
        image: "/images/admissions/iaer-admission-mega-menu-image.webp",
        items: [
            { title: "Overview", href: "/admissions#admissions-overview", icon: "Info" },
            { title: "Admission Criteria", href: "/admissions#admissions-eligibility", icon: "CheckSquare" },
            { title: "How to Apply?", href: "/admissions#admissions-apply", icon: "HelpCircle" },
            { title: "Course Fee", href: "/admissions#admissions-fee", icon: "Banknote" },
            { title: "IAER Scholarships", href: "/admissions#admissions-scholarships", icon: "GraduationCap" },
            { title: "Education Loan", href: "/admissions#admissions-loan", icon: "Coins" },
            { title: "Campus Life", href: "/admissions#admissions-campus", icon: "Smile" },
            { title: "Infrastructure", href: "/infrastructure", icon: "Building2" },
            { title: "Hostel & Student Accommodations", href: "/admissions/hostel-fee", icon: "Hotel" },
        ],
    },
    {
        title: "Placement",
        href: "/placement",
        icon: "Briefcase",
        description: "Internships, career support, and placement assistance.",
        image: "/images/placement/placement-mega-menu-photo.webp",
        items: [
            { title: "Overview", href: "/placement#placement-overview", icon: "Info", description: "Placement philosophy and approach." },
            { title: "Placement Cell (TPC/CSD)", href: "/placement#placement-cell", icon: "Users", description: "Training & Placement Cell and Career Services." },
            { title: "Career Roadmap", href: "/placement#career-model", icon: "Target", description: "Year-wise career development." },
            { title: "Internships", href: "/placement#internships", icon: "Briefcase", description: "Live projects and industry exposure." },
            { title: "Recruiters", href: "/placement#recruiters", icon: "Handshake", description: "Our hiring partners." },
            { title: "Sectors", href: "/placement#sectors", icon: "PieChart", description: "Career opportunities by sector." },
        ],
    },
    {
        title: "Research",
        href: "/research-and-innovation",
        icon: "Microscope",
        description: "Fostering innovation, research, and entrepreneurship.",
        image: "/images/research-and-innovation/research-and-innovation-hero-mega-menu.webp",
        items: [
            { title: "Overview", href: "/research-and-innovation#research-overview", icon: "Info", description: "Research philosophy and impact." },
            { title: "Research Areas", href: "/research-and-innovation#innovation-research", icon: "Microscope", description: "Key domains of inquiry." },
            { title: "Innovation Labs", href: "/research-and-innovation#innovation-research", icon: "Zap", description: "Centers of excellence & tech labs." },
            { title: "Startup Launchpad", href: "/research-and-innovation#startup-entrepreneurship", icon: "Rocket", description: "Incubation & entrepreneurship support." },
            { title: "Mentorship", href: "/research-and-innovation#startup-entrepreneurship", icon: "Users", description: "Guidance from industry leaders." },
            { title: "Funding", href: "/research-and-innovation#startup-entrepreneurship", icon: "Coins", description: "Grants and investment opportunities." },
        ],
    },
    {
        title: "Campus Life",
        href: "/campus-life",
        icon: "Smile",
        description: "Experience the vibrant student community at IAER.",
        image: "/images/hero_images/slider-6.jpg",
        items: [
            { title: "Overview", href: "/campus-life#campus-overview", icon: "Layout", description: "Life beyond classrooms." },
            { title: "Gallery", href: "/campus-life#gallery", icon: "Image", description: "Visual journey of campus life." },
            { title: "Events", href: "/campus-life#events", icon: "Calendar", description: "Cultural & social celebrations." },
            { title: "Clubs", href: "/campus-life#clubs", icon: "Users", description: "Student-led communities." },
        ],
    },
];
